version: "3.9"

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/src
    working_dir: /src
    depends_on:
      - db
    tty: true
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
